// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrDSvOQrVEF9_3kjOZ238qdj2UkMNHtF0',
    appId: '1:1056134144672:web:980aaa2e8e28fec5bd5fc5',
    messagingSenderId: '1056134144672',
    projectId: 'student-manager-2c49f',
    authDomain: 'student-manager-2c49f.firebaseapp.com',
    storageBucket: 'student-manager-2c49f.firebasestorage.app',
    measurementId: 'G-VR3PVJ4KRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-iYUbAH3jLfYXIwsxuSvXIzVMget20g',
    appId: '1:1056134144672:android:78eeee74e67d428fbd5fc5',
    messagingSenderId: '1056134144672',
    projectId: 'student-manager-2c49f',
    storageBucket: 'student-manager-2c49f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLiX6cZlheuKLRnNpfYgeinr5eR9qaDJA',
    appId: '1:1056134144672:ios:aac61ea5c01b994ebd5fc5',
    messagingSenderId: '1056134144672',
    projectId: 'student-manager-2c49f',
    storageBucket: 'student-manager-2c49f.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLiX6cZlheuKLRnNpfYgeinr5eR9qaDJA',
    appId: '1:1056134144672:ios:aac61ea5c01b994ebd5fc5',
    messagingSenderId: '1056134144672',
    projectId: 'student-manager-2c49f',
    storageBucket: 'student-manager-2c49f.firebasestorage.app',
    iosBundleId: 'com.example.studentManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrDSvOQrVEF9_3kjOZ238qdj2UkMNHtF0',
    appId: '1:1056134144672:web:384abf00925940f0bd5fc5',
    messagingSenderId: '1056134144672',
    projectId: 'student-manager-2c49f',
    authDomain: 'student-manager-2c49f.firebaseapp.com',
    storageBucket: 'student-manager-2c49f.firebasestorage.app',
    measurementId: 'G-KYQTYGDC98',
  );
}
